// react-project/src/views/Home.jsx
import React from 'react'
import RouterBtn from '../components/RouterBtn'
import '../styles/views/Home.css'

function HomePage() {
  return (
    <div>
      <p className="title">HOME PAGE</p>
      <RouterBtn path="/second-page" buttonText="Go to 2nd page" />
    </div>
  );
}

export default HomePage;

// vue-project/src/views/Home.vue
<template>
  <p class="title">HOME PAGE</p>
  <LinkBtn
    :path="'/second-page'"
    :buttonText="'Go to 2nd page'">
  </LinkBtn>
</template>


<script setup>
import LinkBtn from '../components/RouterBtn.vue';
</script>


<style scoped>

.title {
  color: red;
  font-family: Arial, sans-serif;
  padding-left: 20px;
}

</style>
