// react-project/src/views/SecondPage.jsx
import { React, useState } from 'react'
import RouterBtn from '../components/RouterBtn'

function SecondPage() {
  const [count, setCount] = useState(0);

  const incrementCount = () => {
    setCount(count + 1);
  };

  return (
    <div>
      <p className="text-purple-500 font-sans">SECOND PAGE</p>
      <RouterBtn path="/" buttonText="Go to Home Page" />
      <div>
        <button onClick={incrementCount}
        className="mt-2 px-4 py-2 text-white bg-gray-500 hover:bg-gray-700">
          Count {count}
        </button>
      </div>
    </div>
  );
}

export default SecondPage;

// vue-project/src/views/SecondPage.vue
<template>
  <p class="title">Second Page</p>
  <LinkBtn
    :path="'/'"
    :buttonText="'Go to Home page'">
  </LinkBtn>
</template>


<script setup>
import LinkBtn from '../components/RouterBtn.vue';
</script>


<style scoped>

.title {
  color: purple;
  font-family: Arial, sans-serif;
  padding-left: 20px;
}

</style>
